version: 2

defaults: &defaults
  docker:
    - image: quay.io/ithacacollege/www-ithaca-ci:latest
  environment:
    TZ: "/usr/share/zoneinfo/America/New_York"
    NOTIFY: 'scripts/github/add-commit-comment {project} {sha} "Created multidev environment [{site}#{env}]({dashboard-url})." {site-url}'
    TERMINUS_SITE: ithaca-www
    TEST_SITE_NAME: Ithaca College
    DEPLOYMENT_BRANCH: develop

jobs:
  init-pantheon:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Initializing terminus and multidev
          command: |
            .circleci/scripts/terminus-env.sh
            source env.sh
            .circleci/scripts/pantheon-reset.sh

  build-drupal:
    <<: *defaults
    steps:
      - checkout
#      - restore_cache:
#          name: Restoring cache: composer dependencies
#          key: composer-{{ checksum "composer-lock.json" }}
      - run:
          name: Installing composer dependencies
          command: |
            .circleci/scripts/github-env.sh
            source env.sh
            .circleci/scripts/build-drupal.sh
      - save_cache:
          name: Saving cache: composer dependecies
          key: composer-{{ checksum "composer-lock.json" }}
          paths:
            - vendor

  build-node:
    <<: *defaults
    steps:
      - checkout
#      - restore_cache:
#          name: Restoring cache: npm install
#          key: theme-npm-{{ checksum "web/themes/custom/ithaca/package-lock.json" }}
      - run:
          name: Installing node dependencies for theme building
          command: |
            .circleci/scripts/build-node.sh
#      - save_cache:
#          key: theme-npm-{{ checksum "web/themes/custom/ithaca/package-lock.json" }}
#          paths:
#            - web/themes/custom/ithaca/node_modules


  report-done:
    docker:
      - image: alpine:3.6
    steps:
      - run:
          name: Complete
          command: echo "Completed build"

workflows:
  version: 2
  build-pr:
    jobs:
      - init-pantheon
      - build-drupal
      - build-node
      - report-done:
          requires:
            - init-pantheon
            - build-drupal
            - build-node
