version: 2

defaults: &defaults
  docker:
    - image: quay.io/ithacacollege/www-ithaca-ci:v2.0.1
  environment:
    TZ: "/usr/share/zoneinfo/America/New_York"

jobs:
  report-environment:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Report environment from shell script
          command: .circleci/scripts/report-environment.sh

  set-env:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Set environment
          command: |
            .circleci/scripts/set-environment.sh
      - persist_to_workspace:
          root: config
          paths:
            - env.sh

  get-env:
    <<: *defaults
    steps:
      - attach_workspace:
          at: config
      - run:
          name: Report environment set by script
          command: |
            source config/env.sh
            echo "TEST:" $TEST
            echo "PR_NUMBER:" $PR_NUMBER
            echo "PR_LABEL:" $PR_LABEL
            echo "CI_LABEL:" $CI_LABEL
            echo "ENV:" $ENV

  report-done:
    <<: *defaults
    steps:
      - run:
          name: Complete
          command: echo "Completed build"

workflows:
  version: 2
  test-workflow:
    jobs:
      - report-environment
      - set-env
      - get-env:
          requires:
            - set-env
      - report-done:
          requires:
            - report-environment
            - get-env
