version: 2

defaults: &defaults
  docker:
    - image: quay.io/ithacacollege/www-ithaca-ci:v2.0.1
  environment:
    TZ: "/usr/share/zoneinfo/America/New_York"

jobs:
  report-env:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Report environment from shell script
          command: |
            .circleci/scripts/report-env.sh
            .circleci/scripts/terminus-env.sh
            source env.sh
            echo "TERMINUS_ENV": $TERMINUS_ENV

#  environment:
#    <<: *defaults
#    steps:
#      - checkout
#      - run:
#          name: Set environment
#          command: |
#            .circleci/scripts/set-environment.sh
#      - persist_to_workspace:
#          root: config
#          paths:
#            - env.sh

#  get-terminusenv:
#    <<: *defaults
#    steps:
#      - attach_workspace:
#          at: config
#      - run:
#          name: Report environment set by script
#          command: |
#            source config/env.sh
#            echo "TEST:" $TEST
#            echo "PR_NUMBER:" $PR_NUMBER
#            echo "PR_LABEL:" $PR_LABEL
#            echo "CI_LABEL:" $CI_LABEL
#            echo "ENV:" $ENV

  report-done:
    docker:
      - image: alpine:3.6
    steps:
      - run:
          name: Complete
          command: echo "Completed build"

workflows:
  version: 2
  test-workflow:
    jobs:
      - report-env:
          filters:
            branches:
              ignore: master
      - report-done:
          requires:
            - report-env
