version: 2

defaults: &defaults
  docker:
    - image: quay.io/ithacacollege/www-ithaca-ci:v2.0.1
  environment:
    TZ: "/usr/share/zoneinfo/America/New_York"

jobs:
  report-environment:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Report environment from shell script
          command: .circleci/scripts/report-environment.sh

  set-script:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Set environment from scripts
          command: ./.circleci/scripts/set-environemt.sh

  get-script:
    <<: *defaults
    steps:
      - run:
          name: Report environment set by script
          command: |
            echo $PR_NUMBER
            echo $PR_LABEL
            echo $CI_LABEL
            echo $ENV

  report-done:
    <<: *defaults
    steps:
      - run:
          name: Complete
          command: echo "Completed build"

workflows:
  version: 2
  test-workflow:
    jobs:
      - report-environment
      - set-script
      - get-script:
          requires:
            - set-script
      - report-done:
          requires:
            - report-environment
            - get-script
